on:
  push:
#    branches: [ main ]
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron:  '12 10 9 * *'

name: Continuous integration

jobs:

  lints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@${{ matrix.rust }}
        with:
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check
      - run: cargo clippy --all

#  build_only:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        target:
#          - thumbv7m-none-eabi
#        rust:
#          - stable
#          - nightly
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: ${{ matrix.rust }}
#          target: ${{ matrix.target }}
#          override: true
#
#      - uses: actions-rs/cargo@v1
#        with:
#          command: build

#  tests:
#    needs: [build_only]
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        target:
#          - x86_64-unknown-linux-gnu
#          - i686-unknown-linux-gnu
#        rust:
#          - stable
#          - nightly
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: ${{ matrix.rust }}
#          target: ${{ matrix.target }}
#          override: true
#
#      - uses: actions-rs/cargo@v1
#        with:
#          command: build
#
#      - uses: actions-rs/cargo@v1
#        with:
#          command: test
#
#  docs:
#    needs: [build_only]
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        rust:
#          - stable
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: ${{ matrix.rust }}
#          override: true
#
#      - uses: actions-rs/cargo@v1
#        with:
#          command: doc
